version: "3.9"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    volumes:
      - ../:/var/www/html/
    ports:
      - 8080:80
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASS: password
      DB_NAME: portfolio
      ENVIRONMENT: DEV
  database:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_ROOT_PASSWORD: password
